services:
- buildCommand: pip install -r backend/requirements.txt
  envVars:
  - key: PORT
    value: '10000'
  - key: MARKET_DATA_API_KEY
    value: QT_wat5QfcJ6N9pDZM5
  - key: ENVIRONMENT
    value: production
  - key: REALTIME_DATA_ENABLED
    value: 'true'
  healthCheckPath: /api/health
  name: realtime-stock-test
  plan: free
  runtime: python3
  startCommand: python backend/app.py
  type: web
