services:
- autoDeploy: true
  buildCommand: pip install -r backend/requirements.txt
  disk:
    mountPath: /opt/render/project/src/data
    name: trading-data
    sizeGB: 1
  envVars:
  - key: PYTHONPATH
    value: /opt/render/project/src
  - key: PORT
    value: '10000'
  - key: ENVIRONMENT
    value: production
  - key: DATABASE_URL
    value: sqlite:///./data/trading.db
  - key: CORS_ORIGINS
    value: '*'
  healthCheckPath: /api/health
  name: trading-backend-api
  plan: free
  runtime: python3
  startCommand: python backend/app.py
  type: web
