# 更新现有的Worker配置
name = "aigupiao-trading-api"
main = "simple-api-worker.js"
compatibility_date = "2024-01-01"

# 路由配置 - 使用现有的路由
routes = [
    { pattern = "api.aigupiao.me/*", zone_name = "aigupiao.me" }
]

# 环境变量
[vars]
ENVIRONMENT = "production"
API_VERSION = "1.0.0"

# 兼容性标志
compatibility_flags = ["nodejs_compat"]
