name = "test-api-backend"
main = "test-worker.js"
compatibility_date = "2024-01-01"

[env.production]
name = "test-api-backend"

[env.production.vars]
ENVIRONMENT = "production"
API_VERSION = "1.0.0"
