# AI股票交易系统 - Cloudflare Workers API配置
name = "aigupiao-api-fixed"
main = "simple-api-worker.js"
compatibility_date = "2024-01-01"

# 生产环境配置
[env.production]
name = "aigupiao-api-fixed"

# 环境变量
[env.production.vars]
ENVIRONMENT = "production"
API_VERSION = "1.0.0"

# 开发环境配置
[env.development]
name = "aigupiao-api-dev"

[env.development.vars]
ENVIRONMENT = "development"
API_VERSION = "1.0.0-dev"

# 兼容性标志
compatibility_flags = ["nodejs_compat"]
