name = "aigupiao-subdomain-router"
main = "worker.js"
compatibility_date = "2024-01-01"
node_compat = true

# 兼容性设置
[build]
command = ""

# 环境变量
[vars]
NODE_VERSION = "20"

[[routes]]
pattern = "aigupiao.me/*"
zone_name = "aigupiao.me"

[[routes]]
pattern = "*.aigupiao.me/*"
zone_name = "aigupiao.me"
